### ISSUE TITLE
Code running

### ISSUE THREAD

**Issue by x12321x** [binh-vu/semantic-modeling#1]
Hello, could you tell me the order in which the files in the bin/experiments directory run?

**Comment by KyrieWang7** [comment]
hello,I do not konw too,could you please tell me the order ?

**Comment by binh-vu** [comment]
Hi, they are formatted like this: `<method>_<dataset>.sh` (e.g., [mira_museum_edm.sh](https://github.com/binh-vu/semantic-modeling/blob/master/bin/experiments/mira_museum_edm.sh)). You can pick any file to run :)
