### ISSUE TITLE
Error when running exp. script

### ISSUE THREAD

**Issue by Averyfork** [binh-vu/semantic-modeling#2]
Hello, can you help me understand what is causing this error?  I tried to run the script ``` mira_ museum_crm.sh```  but encountered the following error：

```
Finished release [optimized] target(s) in 0.08s
     Running `/home/zwfeng2/sm/sm/target/release/exec -i 
'/home/zwfeng2/sm/sm/bin/experiments/debug/experiments/museum_edm_july_27__16:11:14
/kfold-/home/zwfeng2/sm/sm/bin/experiments/debug/museum_edm/cached/semantic_models.json' --- '
<_io.TextIOWrapper' 'name='\''/home/zwfeng2/sm/sm/bin/experiments/debug/museum_edm/cached
/semantic_models.json'\''' 'mode='\''r'\''' 'encoding='\''UTF-8'\''>' s01-to-s14/rust-input.json -c 
/home/zwfeng2/sm/sm/bin/experiments/mira_config.yml exp -g false`

error: Found argument '--' which wasn't expected, or isn't valid in this context

USAGE:
    exec [OPTIONS] -i <input> [SUBCOMMAND]
```

Some of the **debugging information** for the script is as follows.

```
>>>>>> semantic-labeling-method=ReImplMinhISWC, #TYPES=4, KFOLD = {"train_sm_ids": ["s01-s14"], "test_sm_ids": ["s15-s28"]}
Execute: python -m experiments.semantic_modeling.kfold_mira             --dataset=museum_crm             --func=gen_input             --styper=ReImplMinhISWC             --styper_top_n_stypes=4             --styper_simulate_testing=false             --kfold={"train_sm_ids": ["s01-s14"], "test_sm_ids": ["s15-s28"]}             --exp_dir=/home/zwfeng2/sm/sm/bin/experiments/debug/experiments/museum_crm_july_27__16:22:01
/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached/semantic_models.json
---
<_io.TextIOWrapper name='/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached/semantic_models.json' mode='r' encoding='UTF-8'>
```

Attached is my log file. 
[execution.log](https://github.com/binh-vu/semantic-modeling/files/9196540/execution.log)

**Comment by binh-vu** [comment]
Hi, I notice a few things. First in your execution.log, it has this line:

```
  = note: /usr/bin/ld: cannot find -lctensor
          collect2: error: ld returned 1 exit status
```

It shows that the compile process does not succeed. `-lctensor` seems to indicate that it doesn't found the aten library. For an example, you can see [Dockerfile](https://github.com/binh-vu/semantic-modeling/tree/master/containers/dev_environment).

But somehow, you are able to run the script and it shows `Finished release [optimized] target(s) in 0.08s` meaning you can compile it. A bit strange, but assuming it's compiled successfully, I notice that the variable `exp_dir` is

```
--exp_dir=/home/zwfeng2/sm/sm/bin/experiments/debug/experiments/museum_crm_july_27__16:22:01
/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached/semantic_models.json
---
<_io.TextIOWrapper name='/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached/semantic_models.json' mode='r' encoding='UTF-8'>
```

That's why you have that error. It's supposed to be an string of your current directory getting from [the `pwd` command](https://github.com/binh-vu/semantic-modeling/blob/b387584502ba1daa6abd6b7573828416f6426b49/bin/experiments/func/mira_func.sh#L19). I don't know why you have that error, do you run the script using bash? also, can you make sure that $exp_dir is set correctly to see if you have that error again.

**Comment by Averyfork** [comment]
Thank you very much for your reply.  In fact, I have installed the ```ctensor``` and may have uploaded the wrong log file.  With your help, I found that $exp_dir is actually correct.

```
kfold-/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached/semantic_models.json 
--- <_io.TextIOWrapper name='/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached
/semantic_models.json' mode='r' encoding='UTF-8'> s01-to-s14
```

This is the variable ```$rust_dir```, which is generated by [rust_dir="kfold-$(python -m experiments.arg_helper --dataset $dataset --kfold "$kfold" --func get_short_train_name)"](https://github.com/binh-vu/semantic-modeling/blob/b387584502ba1daa6abd6b7573828416f6426b49/bin/experiments/func/mira_func.sh#L57). It calls function [get_short_train_name](https://github.com/binh-vu/semantic-modeling/blob/b387584502ba1daa6abd6b7573828416f6426b49/pysm/semantic_modeling/data_io.py#L44) and produces the above return value. And the variables ```$dataset``` and ```$kfold``` are both correct, ```museum_crm``` and ```{"train_sm_ids": ["s01-s14"], "test_sm_ids": ["s15-s28"]}``` respectively. It seems to generate some redundant information, but I don't know what the reason is. After I deleted the cache file, I still got the same error.

**Comment by binh-vu** [comment]
now it makes sense to me. Can you run:
```
python -m experiments.arg_helper --dataset $dataset --kfold "$kfold" --func get_short_train_name
```
It should just print the string `s01-to-s14`. But in your case, perhaps you print something else in the script.
```
kfold-/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached/semantic_models.json 
--- <_io.TextIOWrapper name='/home/zwfeng2/sm/sm/bin/experiments/debug/museum_crm/cached
/semantic_models.json' mode='r' encoding='UTF-8'>
```
Removing the printing statements and it should work.

**Comment by Averyfork** [comment]
Thanks a lot! I've solved that problem and it is working correctly. However, when I conducted another set of experiments```kfold={"train_sm_ids": ["s15-s28"], "test_sm_ids": ["s01-s14"]}```, I encountered the following error.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
```

This is not a serious issue and has not impacted my usage so far. Anyway, thank you very much for your help, your work is excellent!
Attached is my log file, which includes the stack backtrace.
[execution.log](https://github.com/binh-vu/semantic-modeling/files/9219540/execution.log)

**Comment by Averyfork** [comment]
Sorry to bother you again. I want to use your method on semantic labelers SemTyper. However, the repository in the Dockerfile ```https://github.com//Web-Karma.git``` no longer exists. I have modified the latest version of Web-Karma for use. There are still some details I don't understand, so can you tell me what is the mainclass of the ```karma-research-0.0.1-SNAPSHOT-jar-with-dependencies.jar```? Or could you please provide some guidance? Thank you for your kind cooperation.

**Comment by binh-vu** [comment]
I think you are talking about this [Dockerfile](https://github.com/binh-vu/semantic-modeling/blob/b387584502ba1daa6abd6b7573828416f6426b49/containers/mohsen_jws2015/Dockerfile#L17) to build Web-Karma. Sorry, it is a typo on my side.

The karma repo in that Dockerfile is: [https://github.com/binhlvu/web-karma](https://github.com/binhlvu/web-karma) forked from [usc-isi-i2](https://github.com/usc-isi-i2/web-karma). Just insert the missing username between `//`.

I remember that I specified the mainclass in maven pom.xml so you don't need to worry about that (you can find the main class in the repo). If you want to see how it's called, trace back from [karma_func.sh](https://github.com/binh-vu/semantic-modeling/blob/master/bin/experiments/func/karma_func.sh) in the experiments folder, you can get to [this function calling docker](https://github.com/binh-vu/semantic-modeling/blob/master/pysm/experiments/previous_work/mohsen_jws2015/setup_karma.py)

**Comment by Averyfork** [comment]
Thank you for your prompt reply. I have one last question.  When I want to set parameter ```use_correct_type```, I always get the following error.  What I want to do is to model the data source with the correct semantic types provided by SemTyper. 

Also, you have mentioned in your paper that Oracle semantic labeler always outputs the correct semantic type. Can I treat the oracle results as the same as what I want?

 Thank you again for everything you've done. After that I will close this issue.
```
subprocess.CalledProcessError: Command 'docker run --rm -v /home/zwfeng2/sm/sm/bin/experiments/debug/tmp/mohsen-
styper-s01-to-s15--s17-to-s28/s01-cb:/karma-home -it isi/mohsen_jws2015 -karma_home /karma-home -dataset_name 
museum_crm -use_correct_type true -use_old_semantic_typer true -num_candidate_semantic_type 1 
-multiple_same_property_per_node true -coefficient_coherence 1.0 -coefficient_confidence 1.0 -coefficient_size 0.5 
-num_candidate_mappings 50 -mapping_branching_factor 50 -topk_steiner_tree 10 -cutoff 1000000 -train_source_names s02
-dma,s03-ima-artists,s04-ima-artworks,s05-met,s06-npg,s07-s-13,s08-s-17-edited,s09-s-18-artists,s10-s-18-artworks,s11-s-19
-artists,s12-s-19-artworks,s13-s-art-institute-of-chicago,s14-s-california-african-american,s15-s-detroit-institute-of-art,
s17-s-houston-museum-of-fine-arts,s18-s-indianapolis-artists,s19-s-indianapolis-artworks,s20-s-lacma,s21-s-met,
s22-s-moca,s23-s-norton-simon,s24-s-oakland-museum-paintings,s25-s-san-francisco-moma,s26-s-the-huntington,
s27-wildlife-art,s28-gilcrease -test_source_names s01-cb' returned non-zero exit status 1.

```

**Comment by binh-vu** [comment]
Can you run the docker command separately and post the error here? It's hard to know what's going on without the error message.

> Also, you have mentioned in your paper that Oracle semantic labeler always outputs the correct semantic type. Can I treat the oracle results as the same as what I want?

If you want to model data source given the correct semantic type of each attribute, then yes, you can use the oracle semantic labeler. SemTyper will output top K semantic types and it may contain errors.

**Comment by Averyfork** [comment]
Thank you for your kind help.  I get it and I've solved that problem.
